version: '3.9'

services:
  db:
    image: mysql:8.0
    cap_add: 
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=quotes
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '33000:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    container_name: graph_qldd
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - .:/app


volumes:
  db:
    driver: local
