version: '3.9'

services:
  db:
    image: mysql:5.6
    # cap_add:
    #   - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=tester
      - MYSQL_ROOT_PASSWORD=startmeup
    ports:
      - '33002:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  web:
      build: .
      command: python manage.py runserver localhost:8000
      ports:
        - 8000:8000
      depends_on:
        - db