# Generated by Django 3.2 on 2022-04-18 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20220418_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.playerboard'),
        ),
    ]
